title: Mark Harfouche
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Mark Harfouche.
  Graduate student
  Electrical Engineer
  This website contains awesome information about research, science, engineering
  computer, and cycling.
baseurl: "" # the subpath of your site, e.g. /blog/

# the base hostname & protocol for your site
url: "https://www.markharfouche.com"
enforce_ssl: www.markharfouche.com

port: 8080 # Gets overwritten by github. Need this for testing purposes


exclude: [Gemfile, Gemfile.lock]

google_analytics_id: UA-55670916-1

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"


kramdown:
  input: GFM

