highlighter: pygments
port: 8080
exclude: [Gemfile, Gemfile.lock]

redcarpet:
    extensions: [smart, footnotes, autolink, tables, no_intra_emphasis, disable_indented_code_blocks, space_after_headers]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

markdown: redcarpet

#kramdown:
  #input: GFM

