highlighter: pygments
port: 8080
exclude: [Gemfile, Gemfile.lock]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

kramdown:
  input: GFM
