title: Mark Harfouche
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Mark Harfouche.
  Graduate student
  Electrical Engineer
  This website contains awesome information about research, science, engineering
  computer, and cycling.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.markharfouche.com" # the base hostname & protocol for your site
highlighter: pygments

port: 8080 # Gets overwritten by github. Need this for testing purposes

markdown: redcarpet

exclude: [Gemfile, Gemfile.lock]

redcarpet:
    extensions: [smart, footnotes, autolink, tables, no_intra_emphasis, disable_indented_code_blocks, space_after_headers]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"


#kramdown:
  #input: GFM

